<a href="https://colab.research.google.com/github/holegar/datasharing/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 8 Exercises
Let's practice what we have learnt on numpy library

import NumPy as np

In [ ]:
import numpy as np

In [ ]:
b = np.arange(1,28)

In [ ]:
b = b.reshape(3,3,3)

In [ ]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
b[0,1,1]

5

In [ ]:
Create an array of 20 zeros

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
Create an array of 20 ones

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Create an array of 20 threes

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
[3]*20

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3.])

In [ ]:
Create an array of integers from 5 to 100

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100])

create an array of even numbers from 10 to 1000

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.arange(10,1000,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112,
       114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
       140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164,
       166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190,
       192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216,
       218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242,
       244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268,
       270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294,
       296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320,
       322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346,
       348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372,
       374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398,
       400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 422, 424,
       426, 428, 430, 432, 434, 436, 438, 440, 442, 444, 446, 448, 450,
       452, 454, 456, 458, 460, 462, 464, 466, 468, 470, 472, 474, 476,
       478, 480, 482, 484, 486, 488, 490, 492, 494, 496, 498, 500, 502,
       504, 506, 508, 510, 512, 514, 516, 518, 520, 522, 524, 526, 528,
       530, 532, 534, 536, 538, 540, 542, 544, 546, 548, 550, 552, 554,
       556, 558, 560, 562, 564, 566, 568, 570, 572, 574, 576, 578, 580,
       582, 584, 586, 588, 590, 592, 594, 596, 598, 600, 602, 604, 606,
       608, 610, 612, 614, 616, 618, 620, 622, 624, 626, 628, 630, 632,
       634, 636, 638, 640, 642, 644, 646, 648, 650, 652, 654, 656, 658,
       660, 662, 664, 666, 668, 670, 672, 674, 676, 678, 680, 682, 684,
       686, 688, 690, 692, 694, 696, 698, 700, 702, 704, 706, 708, 710,
       712, 714, 716, 718, 720, 722, 724, 726, 728, 730, 732, 734, 736,
       738, 740, 742, 744, 746, 748, 750, 752, 754, 756, 758, 760, 762,
       764, 766, 768, 770, 772, 774, 776, 778, 780, 782, 784, 786, 788,
       790, 792, 794, 796, 798, 800, 802, 804, 806, 808, 810, 812, 814,
       816, 818, 820, 822, 824, 826, 828, 830, 832, 834, 836, 838, 840,
       842, 844, 846, 848, 850, 852, 854, 856, 858, 860, 862, 864, 866,
       868, 870, 872, 874, 876, 878, 880, 882, 884, 886, 888, 890, 892,
       894, 896, 898, 900, 902, 904, 906, 908, 910, 912, 914, 916, 918,
       920, 922, 924, 926, 928, 930, 932, 934, 936, 938, 940, 942, 944,
       946, 948, 950, 952, 954, 956, 958, 960, 962, 964, 966, 968, 970,
       972, 974, 976, 978, 980, 982, 984, 986, 988, 990, 992, 994, 996,
       998])

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  310,  312,  314,  316,
        318,  320,  322,  324,  326,  328,  330,  332,  334,  336,  338,
        340,  342,  344,  346,  348,  350,  352,  354,  356,  358,  360,
        362,  364,  366,  368,  370,  372,  374,  376,  378,  380,  382,
        384,  386,  388,  390,  392,  394,  396,  398,  400,  402,  404,
        406,  408,  410,  412,  414,  416,  418,  420,  422,  424,  426,
        428,  430,  432,  434,  436,  438,  440,  442,  444,  446,  448,
        450,  452,  454,  456,  458,  460,  462,  464,  466,  468,  470,
        472,  474,  476,  478,  480,  482,  484,  486,  488,  490,  492,
        494,  496,  498,  500,  502,  504,  506,  508,  510,  512,  514,
        516,  518,  520,  522,  524,  526,  528,  530,  532,  534,  536,
        538,  540,  542,  544,  546,  548,  550,  552,  554,  556,  558,
        560,  562,  564,  566,  568,  570,  572,  574,  576,  578,  580,
        582,  584,  586,  588,  590,  592,  594,  596,  598,  600,  602,
        604,  606,  608,  610,  612,  614,  616,  618,  620,  622,  624,
        626,  628,  630,  632,  634,  636,  638,  640,  642,  644,  646,
        648,  650,  652,  654,  656,  658,  660,  662,  664,  666,  668,
        670,  672,  674,  676,  678,  680,  682,  684,  686,  688,  690,
        692,  694,  696,  698,  700,  702,  704,  706,  708,  710,  712,
        714,  716,  718,  720,  722,  724,  726,  728,  730,  732,  734,
        736,  738,  740,  742,  744,  746,  748,  750,  752,  754,  756,
        758,  760,  762,  764,  766,  768,  770,  772,  774,  776,  778,
        780,  782,  784,  786,  788,  790,  792,  794,  796,  798,  800,
        802,  804,  806,  808,  810,  812,  814,  816,  818,  820,  822,
        824,  826,  828,  830,  832,  834,  836,  838,  840,  842,  844,
        846,  848,  850,  852,  854,  856,  858,  860,  862,  864,  866,
        868,  870,  872,  874,  876,  878,  880,  882,  884,  886,  888,
        890,  892,  894,  896,  898,  900,  902,  904,  906,  908,  910,
        912,  914,  916,  918,  920,  922,  924,  926,  928,  930,  932,
        934,  936,  938,  940,  942,  944,  946,  948,  950,  952,  954,
        956,  958,  960,  962,  964,  966,  968,  970,  972,  974,  976,
        978,  980,  982,  984,  986,  988,  990,  992,  994,  996,  998,
       1000])

In [ ]:
Create a 5 by 5 matrix with values ranging between 0 and 10

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.random.randint(0,10,25).reshape(5,5)

array([[3, 3, 8, 3, 9],
       [6, 0, 5, 6, 6],
       [2, 9, 1, 2, 6],
       [0, 4, 0, 4, 0],
       [2, 2, 3, 3, 6]])

array([[ 0,  7,  6,  4,  0],
       [ 7, 10,  2,  7,  0],
       [ 1,  0, 10,  7,  2],
       [ 3,  9,  3, 10,  9],
       [ 9,  8,  2, 10,  8]])

Create a 5 by 5 identity matrix

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generate an array of 250 random numbers sampled from standard normal distribution

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.random.randint()

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
        177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
        190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200],
       [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
        214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226,
        227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
        240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250],
       [251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
        264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,
        277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
        290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300],
       [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313,
        314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
        327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
        340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350],
       [351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
        364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
        377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
        390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400],
       [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
        414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
        427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
        440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450],
       [451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463,
        464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476,
        477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489,
        490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500]])

array([-1.26172415e+00, -1.88004913e+00, -1.78221646e-03, -9.49368373e-01,
       -1.28635291e+00, -1.16684873e-01,  1.09314519e-01, -1.44235016e+00,
       -2.50381281e+00, -1.20626710e-01, -8.23380413e-01,  1.58411253e+00,
        6.73867082e-01,  3.05541045e-01,  6.41824429e-01, -4.97812470e-01,
        1.03882111e+00,  8.35774515e-01, -4.42634475e-01,  3.21961582e-01,
       -1.04939805e+00, -1.35675983e+00, -9.78392088e-02,  6.94794785e-01,
       -1.72403541e+00,  6.76724239e-01, -1.12049796e+00, -1.42832141e+00,
        3.45615137e-01,  2.31570753e+00, -3.22010051e-01, -9.36094029e-01,
       -1.12869733e+00, -1.51811112e+00,  5.31068142e-01, -5.49224672e-01,
        9.88034848e-01,  1.57788504e+00, -2.35876171e-01, -1.02231714e+00,
        1.28647825e+00, -6.30679426e-01, -1.03682363e-02, -6.23531394e-01,
        1.25841584e-01,  9.67428245e-01,  1.65107505e-03,  7.75764219e-01,
       -1.12573737e-01,  1.49043785e+00, -3.21087399e-01,  2.80119340e-01,
       -8.25276617e-01, -8.05662005e-01,  9.26820680e-01, -5.96546655e-01,
       -5.06141286e-01,  6.32188141e-01, -3.09799200e-03,  1.97469186e+00,
        7.21677384e-01, -1.13136505e+00, -1.75339894e+00,  7.39015512e-02,
       -1.61811043e+00, -9.02678912e-01, -1.76653331e-01, -6.96673682e-02,
        7.66344597e-01,  2.52120849e-01, -1.51388866e+00, -1.70769797e+00,
        2.93930574e-01, -1.66432419e+00,  1.65209899e+00,  8.09509692e-01,
       -3.38973033e-02, -8.17839429e-01,  6.08157557e-01, -1.93896248e-01,
       -8.40791688e-01,  1.42906003e+00, -2.16550438e-01,  1.67533453e-01,
       -4.12905906e-01,  8.24469220e-01, -1.45789665e+00, -7.33734984e-01,
       -5.35501515e-01, -1.59932627e-01,  1.52878690e+00,  2.02859403e-01,
       -2.59378042e-01,  9.46879477e-01, -1.74154731e+00, -9.29032478e-01,
        9.38452070e-02, -2.75633720e-01,  5.03136550e-01, -2.57210570e+00,
       -1.71178806e+00,  6.00023564e-01, -1.67190870e+00,  9.31304316e-01,
        2.05268807e+00,  5.82529543e-02,  9.60049726e-02, -1.24033250e+00,
        8.26312070e-02,  5.74177650e-01,  3.53109542e-01,  1.02126953e+00,
       -4.32813971e-01, -2.79136338e-01,  4.47529350e-01, -9.71544728e-02,
        4.63875578e-02, -5.44745088e-01, -6.10848028e-01, -3.94513919e-01,
       -5.86494866e-02,  1.39472337e+00, -2.20152525e+00,  1.07506594e+00,
        1.33005560e+00,  1.70857872e+00, -1.00361910e+00,  4.09352433e-01,
       -1.75075228e+00,  6.07296069e-01,  8.47640004e-01,  1.24542774e+00,
        2.26649587e-01,  1.35041233e+00, -1.37349082e+00,  5.66193624e-01,
        1.67687229e-01, -4.14721401e-01, -1.00725388e+00,  1.54298509e+00,
       -1.44771612e+00,  8.71591798e-01, -1.42382495e+00, -4.26560331e-01,
       -2.35952330e-01,  1.06749454e+00,  2.13267886e+00, -1.58572126e+00,
       -1.04099020e+00,  4.52681695e-01,  4.99268170e-01, -1.19314667e+00,
       -4.24599451e-01, -1.00390907e+00, -1.05578632e+00,  2.02143642e+00,
       -4.46447002e-01,  6.55187558e-02, -1.75384536e-01,  2.27427271e+00,
       -2.83817226e-01, -5.49925672e-01, -8.55994169e-01, -7.57477756e-01,
       -1.63375622e+00,  3.54783831e-01, -7.27694422e-01,  6.85203712e-01,
        5.85860105e-02, -6.48067706e-02,  8.21642880e-01,  1.74251558e+00,
       -2.67285860e-02,  1.95022130e-01, -2.76903279e+00,  6.55327813e-01,
       -7.92673820e-01,  2.22539083e+00,  4.81570114e-01,  9.13588555e-02,
        2.54288665e-01, -1.75723992e+00, -6.31635437e-01, -1.73661277e+00,
       -1.92934897e-02, -3.72562554e-01, -1.76437666e+00, -7.58258397e-01,
        2.18964994e+00, -1.28829302e+00,  7.92222336e-01, -4.61400138e-01,
        7.30658636e-01, -2.07195322e+00, -3.02153047e-01, -8.11165264e-01,
       -2.25414185e-01, -6.31616279e-01, -1.09277150e+00,  1.17865930e-01,
        7.34068490e-02, -7.28234069e-01,  7.18890908e-01,  4.28429563e-01,
        3.50967780e-01,  3.05019549e-01, -1.47457494e-01, -1.02757399e+00,
       -2.79643534e-01, -1.65379813e+00,  5.11196943e-01,  7.09316674e-01,
        3.75033509e-01,  9.11347604e-01, -1.27052396e-02, -2.26723139e+00,
        2.11544390e-01, -6.77771747e-01, -1.17662872e+00, -2.13813666e-02,
       -1.65840991e+00, -1.23900772e+00,  2.67061655e-02, -2.01368036e-01,
       -2.92300974e-01, -1.46110219e+00, -3.22812345e+00,  4.15754573e-01,
        1.57084629e-01,  4.62289899e-01,  2.75343695e+00, -2.58002690e-02,
        1.32352278e+00,  9.46134005e-01,  7.44365048e-01, -1.86492900e-01,
       -9.08798337e-01,  3.81379846e-01, -6.76843944e-01, -3.14406999e-01,
        4.26552926e-01,  6.24161965e-01,  1.03630337e+00,  4.66940439e-01,
       -5.05898346e-01, -8.16430196e-01,  4.72488721e-01, -1.65542101e+00,
       -1.17707971e+00, -6.82383181e-01])

Create the following matrix

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
np.linspace(0,2,50)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
         1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
         2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
         3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
         4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,
         6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,
         7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,
         8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,
         9.5,  9.6,  9.7,  9.8,  9.9, 10. ],
       [10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1,
        11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2,
        12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2, 13.3,
        13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4,
        14.5, 14.6, 14.7, 14.8, 14.9, 15. ],
       [15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1,
        16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2,
        17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3,
        18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4,
        19.5, 19.6, 19.7, 19.8, 19.9, 20. ],
       [20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1,
        21.2, 21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2,
        22.3, 22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3,
        23.4, 23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4,
        24.5, 24.6, 24.7, 24.8, 24.9, 25. ],
       [25.1, 25.2, 25.3, 25.4, 25.5, 25.6, 25.7, 25.8, 25.9, 26. , 26.1,
        26.2, 26.3, 26.4, 26.5, 26.6, 26.7, 26.8, 26.9, 27. , 27.1, 27.2,
        27.3, 27.4, 27.5, 27.6, 27.7, 27.8, 27.9, 28. , 28.1, 28.2, 28.3,
        28.4, 28.5, 28.6, 28.7, 28.8, 28.9, 29. , 29.1, 29.2, 29.3, 29.4,
        29.5, 29.6, 29.7, 29.8, 29.9, 30. ],
       [30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
        31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
        32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33. , 33.1, 33.2, 33.3,
        33.4, 33.5, 33.6, 33.7, 33.8, 33.9, 34. , 34.1, 34.2, 34.3, 34.4,
        34.5, 34.6, 34.7, 34.8, 34.9, 35. ],
       [35.1, 35.2, 35.3, 35.4, 35.5, 35.6, 35.7, 35.8, 35.9, 36. , 36.1,
        36.2, 36.3, 36.4, 36.5, 36.6, 36.7, 36.8, 36.9, 37. , 37.1, 37.2,
        37.3, 37.4, 37.5, 37.6, 37.7, 37.8, 37.9, 38. , 38.1, 38.2, 38.3,
        38.4, 38.5, 38.6, 38.7, 38.8, 38.9, 39. , 39.1, 39.2, 39.3, 39.4,
        39.5, 39.6, 39.7, 39.8, 39.9, 40. ],
       [40.1, 40.2, 40.3, 40.4, 40.5, 40.6, 40.7, 40.8, 40.9, 41. , 41.1,
        41.2, 41.3, 41.4, 41.5, 41.6, 41.7, 41.8, 41.9, 42. , 42.1, 42.2,
        42.3, 42.4, 42.5, 42.6, 42.7, 42.8, 42.9, 43. , 43.1, 43.2, 43.3,
        43.4, 43.5, 43.6, 43.7, 43.8, 43.9, 44. , 44.1, 44.2, 44.3, 44.4,
        44.5, 44.6, 44.7, 44.8, 44.9, 45. ],
       [45.1, 45.2, 45.3, 45.4, 45.5, 45.6, 45.7, 45.8, 45.9, 46. , 46.1,
        46.2, 46.3, 46.4, 46.5, 46.6, 46.7, 46.8, 46.9, 47. , 47.1, 47.2,
        47.3, 47.4, 47.5, 47.6, 47.7, 47.8, 47.9, 48. , 48.1, 48.2, 48.3,
        48.4, 48.5, 48.6, 48.7, 48.8, 48.9, 49. , 49.1, 49.2, 49.3, 49.4,
        49.5, 49.6, 49.7, 49.8, 49.9, 50. ]])

In [ ]:
Let's generate an array of 50 linearly spaced elements between 0 and 1

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
#Numpy Indexing and Slicing using the provided matrices. You need to replicate the matrix's outputs

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below

In [ ]:
d_mat = np.arange(1,51).reshape(5,10)
d_mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
#Slice the array to produce the array below  #Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat[2:,1:]

array([[22, 23, 24, 25, 26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [42, 43, 44, 45, 46, 47, 48, 49, 50]])

array([[22, 23, 24, 25, 26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat[2,7]

28

28

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat[:4,2:3]

array([[ 3],
       [13],
       [23],
       [33]])

array([[ 3],
       [13],
       [23],
       [33]])

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [ ]:
#compute the sum of all elements of d_mat

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.sum()

1275

1275

In [ ]:
#Compute the standard deviation

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.std()

14.430869689661812

14.430869689661812

In [ ]:
#compute the mean

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.mean()

25.5

25.5

In [ ]:
#compute the variance

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.var()

208.25

208.25

In [ ]:
#Compute the sum of all columns

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.sum(axis=0)

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

In [ ]:
#compute the sum of all rows

In [ ]:
#Write your answer here in order not to overwrite the output, you wont be able to see the output if you write your code in the cell below
d_mat.sum(axis=1)

array([ 55, 155, 255, 355, 455])

In [ ]:
array([9, 9, 9, 9, 9])

# Data File Processing Using NumPy

In [ ]:
# Copyright 2016 Enthought, Inc. All Rights Reserved
"""
Wind Statistics
----------------

Topics: Using array methods over different axes, fancy indexing.

1. The data file 'wind.data' is in the week 9\Tutorial folder and has the following format:

        61  1  1 15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83 12.58 18.50 15.04
        61  1  2 14.71 16.88 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
        61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.50  7.67 12.75 12.71

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.

   Use the 'loadtxt' function from numpy to read the data into
   an array.

2. Calculate the min, max and mean windspeeds and standard deviation of the
   windspeeds over all the locations and all the times (a single set of numbers
   for the entire dataset).

3. Calculate the min, max and mean windspeeds and standard deviations of the
   windspeeds at each location over all the days (a different set of numbers
   for each location)

4. Calculate the min, max and mean windspeed and standard deviations of the
   windspeeds across all the locations at each day (a different set of numbers
   for each day)

5. Find the location which has the greatest windspeed on each day (an integer
   column number for each day).

6. Find the year, month and day on which the greatest windspeed was recorded.

7. Find the average windspeed in January for each location.

You should be able to perform all of these operations without using a for
loop or other looping construct.

In [ ]:
#tinyurl.com/3kbhprak

In [63]:
import numpy as np
from numpy import loadtxt
#f = open("wind.data", "r")
#a = np.array(f.read().split())
wind = loadtxt('wind.data')
data = wind[:, 3:]

print("Total:")
print("Minimum speed: ", data.min())
print("Maximum speed: ", data.max())
print("Mean speed: ", round(data.mean(),2))
print("Standard deviation: ", round(data.std(),2))

print("\nEach location: ")
print("Minimum speeds: ", data.min(axis=0))
print("Maximum speeds: ", data.max(axis=0))
print("Mean speeds: ", data.mean(axis=0))
print("Standard deviation: ", data.std(axis=0))

print("\nEach day: ")
print("Minimum speeds: ", data.min(axis=1))
print("Maximum speeds: ", data.max(axis=1))
print("Mean speeds: ", data.mean(axis=1))
print("Standard deviation: ", data.std(axis=1))

print("\nMaximum location of each day: ")
print(np.argmax(data, axis=1))

print("\nDate of highest record:")
loc2 = np.where(data == data.max())
year = wind[loc2[0], 0]
month = wind[loc2[0],1]
day = wind[loc2[0],2]
print(f"{int(year)+1900}/{int(month)}/{int(day)}")
print("To check: ", wind[loc2[0]])

#Q7
print("\nJanuary Statistics:")
jan_indices = wind[:,1] == 1
jan_data = data[jan_indices]
print('Mean: ', jan_data.mean(axis=0))

Total:
Minimum speed:  0.0
Maximum speed:  42.54
Mean speed:  10.23
Standard deviation:  5.6

Each location:
Minimum speeds:  [0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
Maximum speeds:  [35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
Mean speeds:  [12.36371463 10.64644813 11.66010344  6.30627472 10.45688013  7.09225434
  9.7968345   8.49442044  8.49581838  8.70726803 13.121007   15.59946152]
Standard deviation:  [5.61918301 5.26820081 5.00738377 3.60513309 4.93536333 3.96838126
 4.97689374 4.49865783 4.16746101 4.50327222 5.83459319 6.69734719]

Each day:
Minimum speeds:  [9.29 6.5  6.17 ... 8.71 9.13 9.59]
Maximum speeds:  [18.5  17.54 18.5  ... 29.58 28.79 27.29]
Mean speeds:  [13.09666667 11.79833333 11.34166667 ... 14.89       15.3675
 15.4025    ]
Standard deviation:  [2.5773188  3.28972854 3.50543348 ... 5.51175108 5.30456427 5.45971172]

Maximum location of each day:
[10 10  0 ... 11 11  2]

Date of highest record:
1966/12/2
To check:  [[66.   12.    2.   28.21 27.37 22.54 20.62 22.08 16.13 28.16 17.29 22.5
  23.16 25.88 42.54]]

January Statistics:
Mean:  [14.86955197 12.92166667 13.29962366  7.19949821 11.67571685  8.05483871
 11.81935484  9.5094086   9.54320789 10.05356631 14.55051971 18.02876344]